/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Empresa: typeof import('./src/components/Empresa/Empresa.vue')['default']
    Fornecedor: typeof import('./src/components/Fornecedor/Fornecedor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeDash: typeof import('./src/components/HomeDash.vue')['default']
    HomeDashCard: typeof import('./src/components/HomeDashCard.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
